[theme]
primaryColor="#FFD100"         # Intertek Yellow for highlights
backgroundColor="#F7F9FC"      # Light gray-blue background
secondaryBackgroundColor="#FFFFFF"  # White for cards/content
textColor="#000000"            # Black text
font="sans serif"
